# Site settings
title: "mtiennnnn's Blog"
bye_message: "Bye!"
baseurl: "/"
url: "https://mtiennnnn.github.io"
disqus: mtiennnnn

# Header settings
nick: "mtiennnnn"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "mtiennnnn"
blog:
    server: "wordpress.com"
    nick: "mtiennnnn"
fingerprint_key: 

# Build settings
markdown: kramdown
permalink: /:categories/:title/
