# Site settings
title: "mtiennnnn"
bye_message: "Bye!"
baseurl: "/"
url: "https://mtiennnnn.github.io"
disqus: mtiennnnn

# Header settings
nick: "mtiennnnn"
source_code:
    server: "github.com"
    nick: "mtiennnnn"

# Build settings
markdown: kramdown
permalink: /:categories/
